apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: crossplane
  namespace: crossplane-system
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
  chart:
    repoURL: "{{ .Values.setupArtifactory }}/v{{ .Values.crossplaneSetupVersion }}/crossplane-setup-{{ .Values.crossplaneSetupVersion }}.tgz"
---
kind: Namespace
apiVersion: v1
metadata:
  name: crossplane-system